# Generated by Django 2.0 on 2019-07-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_auto_20190728_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='resumtion_date',
            new_name='resumption_date',
        ),
    ]
